"""add document_ids to chat_sessions for multi-doc chat

Revision ID: a23fa09e7c11
Revises: ad3336a64e49
Create Date: 2026-04-03 22:43:09.001591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a23fa09e7c11'
down_revision: Union[str, Sequence[str], None] = 'ad3336a64e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # NOTE: Keeping ix_document_chunks_embedding HNSW index
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'document_ids')
    # ### end Alembic commands ###
